[tool.briefcase]
project_name = "AttendanceApp"
bundle = "com.om.edu"
version = "1.0.0"

[tool.briefcase.app.attendanceapp]
formal_name = "Student Attendance"
description = "تطبيق رصد الحضور والسلوك"
sources = ["src/attendanceapp"]
requires = [
    "toga-ios",
    "pandas",
    "openpyxl",
    "fpdf2",
]

# الحقول المطلوبة/المستحسنة
author = "Your Name"
url = "https://github.com/USERNAME/REPO"
license = "MIT"
